# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Business' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Business

  target 'BusinessTests' do
    # Pods for testing
  end

end

target 'Core' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Core

  target 'CoreTests' do
    # Pods for testing
  end

end

target 'SPBus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  # Pods for SPBus

  target 'SPBusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SPBusUITests' do
    # Pods for testing
  end

end
